name: Commit and Push

on:
  workflow_dispatch:

jobs:
  commit_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Create file
        run: date >> test.text

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update"
          git push
