on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - uses: Kentama7/hello-world-composite-run-steps-action@v1
        with:
          who-to-greet: 'Ichiro'
      - uses: Kentama7/hello-world-composite-run-steps-action@v1
        with:
          who-to-greet: 'Jiro'
      - uses: Kentama7/private-hello-world-composite-run-steps-action@v1
        with:
          who-to-greet: 'Saburo'