name: try gh

on:
  workflow_dispatch:

jobs:
  gh:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - name: バージョン
        run: |
          gh --version

      - name: PRリスト
        run: |
          gh pr list
          
      - name: wリスト
        run: |
          gh workflow list
