name: try gh

on:
  workflow_dispatch:

jobs:
  gh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: ghいろいろ
        run: |
          gh --version
          gh pr list
          gh workflow list
