name: try gh

on:
  workflow_dispatch:

jobs:
  gh:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - name: バージョン
        run: |
          gh --version

      - name: PRリスト
        run: |
          gh pr list
          
      - name: PRを作る
        run: |
          date +%Y-%m-%dT%H:%M:%S >> README.md
          gh pr create --title "Update README.md" --body "Everything works again"
