name: try gh

on:
  workflow_dispatch:

jobs:
  gh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: バージョン
        run: |
          gh --version
      - name: ログイン
        run: |
          gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
      - name: PRリスト
        run: |
          gh pr list
          
      - name: wリスト
        run: |
          gh workflow list
