name: try gh

on:
  workflow_dispatch:

jobs:
  gh:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - name: バージョン
        run: |
          gh --version

      - name: PRリスト
        run: |
          gh pr list
          
      - name: PRを作る
        run: |
          date >> README.md
          git config user.name ${{ secrets.GIT_ACCOUNT }}
          git config user.email ${{ secrets.GIT_EMAIL }}
          git switch -c update_readme
          git add .
          git commit -m "Update README.md"
          git push
          gh pr create --title "Update README.md" --body "Everything works again"
